### ISSUE TITLE
Changing the border color of a copy of a box can change the color of the original

### ISSUE THREAD

**Issue by rigdern** [boxer-project/boxer-sunrise#99]
# Repro steps
I reproed this with Boxer `3.4.19 2024-06-24`

1. Create a data box by hitting the `{` key
2. Put the cursor into the box
3. Use the menu to change its border color to "red"
4. Use the mouse to select the box
5. Copy the box with command-c
6. Paste the box with command-p
7. Put the cursor into the copy of the box
8. Use the menu to change its border color to "green"

**Expected result:** The copy of the box now has a green border. The original box retains its red border.

**Actual result:** Both boxes now have a green border. Screenshot:
<img width="94" alt="image" src="https://github.com/boxer-project/boxer-sunrise/assets/199935/1ba690e3-9226-457f-a8d2-c9eb00593bdc">

**Comment by sgithens** [comment]
@rigdern Thanks, this is a really good catch. I'm missing a `copy-tree` in the `copy-css-styles-special-property` and `print-vc-css-styles-hook` in the CSS Styles plist entry on boxes... so the reference is getting copied during virtual-copy/evaluation and thusly updated on all it's copies.  

Fixed in 02634f0 , will be in the July build 3.4.20.

**Comment by rigdern** [comment]
I confirmed this no longer repros in Boxer version `3.4.20 2024-08-06`
